### ISSUE TITLE
RuntimeError: The size of tensor a (128) must match the size of tensor b (32) at non-singleton dimension 3

### ISSUE THREAD

**Issue by President-T** [atong01/conditional-flow-matching#71]
python3 train_cifar10.py --model "fm" --lr 2e-4 --ema_decay 0.9999 --batch_size 128 --total_steps 400001 --save_step 20000：
bug：
Traceback (most recent call last):
  File "/t9k/mnt/pycharm_project/conditional-flow-matching-main/examples/cifar10/train_cifar10.py", line 165, in <module>
    app.run(train)
  File "/t9k/mnt/.conda/envs/torchcfm/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/t9k/mnt/.conda/envs/torchcfm/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/t9k/mnt/pycharm_project/conditional-flow-matching-main/examples/cifar10/train_cifar10.py", line 139, in train
    t, xt, ut = FM.sample_location_and_conditional_flow(x0, x1)     # xt = self.sample_xt(x0, x1, t, eps)
  File "/t9k/mnt/pycharm_project/conditional-flow-matching-main/torchcfm/conditional_flow_matching.py", line 185, in sample_location_and_conditional_flow
    xt = self.sample_xt(x0, x1, t, eps)
  File "/t9k/mnt/pycharm_project/conditional-flow-matching-main/torchcfm/conditional_flow_matching.py", line 123, in sample_xt
    mu_t = self.compute_mu_t(x0, x1, t)
  File "/t9k/mnt/pycharm_project/conditional-flow-matching-main/torchcfm/conditional_flow_matching.py", line 329, in compute_mu_t
    return t * x1
RuntimeError: The size of tensor a (128) must match the size of tensor b (32) at non-singleton dimension 3

May I ask how to solve this bug？

**Comment by President-T** [comment]
I made the following modifications to resolve the issue：
t = t.view(128, 1, 1, 1)
